"""
Copy the Nastran/Epilysis H5 matrices file to the repo data folder.

The H5 file is generated by Nastran (not META) and contains M, K matrices
and node coordinates. This script just copies it to the right output folder.

Run from inside META or directly from Python:
    py -3 export_matrices.py

Output (in data/ansa_model/<variant>/):
    matrices.h5
"""

import shutil
from config import INPUT_MATRICES_H5, OUTPUT_DIR


def main():
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    if not INPUT_MATRICES_H5.exists():
        raise FileNotFoundError(
            f"H5 file not found:\n  {INPUT_MATRICES_H5}\n"
            "Check the 'matrices_h5' path in config.py."
        )

    dest = OUTPUT_DIR / "matrices.h5"
    shutil.copy2(INPUT_MATRICES_H5, dest)
    size_mb = dest.stat().st_size / 1024 / 1024
    print(f"Copied {INPUT_MATRICES_H5.name} → {dest}  ({size_mb:.1f} MB)")


if __name__ == '__main__':
    main()
