"""
Handle K/M matrix files for the active variant.

TB  — copies the Nastran/Epilysis H5 file (generated by the getKM run) to
      the repo data folder. The H5 contains M, K matrices and node coords.

BIW — no H5 is available; K.npz and M.npz are written directly by the META
      getKM macro. This branch just verifies that both files are present.

Run from inside META or directly from Python:
    py -3 export_matrices.py

Output (in data/ansa_model/<variant>/):
    TB  → matrices.h5
    BIW → K.npz, M.npz  (must already exist)
"""

import shutil
from config import VARIANT, OUTPUT_DIR, INPUT_MATRICES_H5


def _export_tb():
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    if not INPUT_MATRICES_H5.exists():
        raise FileNotFoundError(
            f"H5 file not found:\n  {INPUT_MATRICES_H5}\n"
            "Check the 'matrices_h5' path in config.py."
        )

    dest = OUTPUT_DIR / "matrices.h5"
    shutil.copy2(INPUT_MATRICES_H5, dest)
    size_mb = dest.stat().st_size / 1024 / 1024
    print(f"Copied {INPUT_MATRICES_H5.name} → {dest}  ({size_mb:.1f} MB)")


def _verify_biw():
    missing = []
    for name in ("K.npz", "M.npz"):
        path = OUTPUT_DIR / name
        if path.exists():
            size_mb = path.stat().st_size / 1024 / 1024
            print(f"  OK  {name}  ({size_mb:.1f} MB)")
        else:
            print(f"  MISSING  {name}")
            missing.append(name)

    if missing:
        raise FileNotFoundError(
            f"Matrix files not found: {', '.join(missing)}\n"
            f"Run the META getKM macro and export to:\n  {OUTPUT_DIR}"
        )

    print("All BIW matrix files present.")


def main():
    print(f"Variant : {VARIANT}")
    print(f"Output  : {OUTPUT_DIR}\n")

    if VARIANT == "TB":
        _export_tb()
    else:
        _verify_biw()


if __name__ == '__main__':
    main()
