"""
Handle K/M matrix files for the active variant.

TB  — copies the Nastran/Epilysis H5 file (generated by the getKM run) to
      the repo data folder. The H5 contains M, K matrices and node coords.

BIW — no H5 is available; K.npz and M.npz are written directly by the META
      getKM macro. This branch just verifies that both files are present.

Run from inside META or directly from Python:
    py -3 export_matrices.py

Output (in data/ansa_model/<variant>/):
    TB  → matrices.h5
    BIW → K.npz, M.npz  (must already exist)
"""

import shutil
from config import VARIANT, OUTPUT_DIR_MATRICES as OUTPUT_DIR
if VARIANT == "BIW":
    from config import INPUT_MATRICES_K, INPUT_MATRICES_M
elif VARIANT == "TB":
    from config import INPUT_MATRICES_H5
else:
    raise ValueError(f"Unknown VARIANT '{VARIANT}' in config.py. Expected 'TB' or 'BIW'.")


def _export_tb():
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    if not INPUT_MATRICES_H5.exists():
        raise FileNotFoundError(
            f"H5 file not found:\n  {INPUT_MATRICES_H5}\n"
            "Check the 'matrices_h5' path in config.py."
        )

    dest = OUTPUT_DIR / "matrices.h5"
    shutil.copy2(INPUT_MATRICES_H5, dest)
    size_mb = dest.stat().st_size / 1024 / 1024
    print(f"Copied {INPUT_MATRICES_H5.name} → {dest}  ({size_mb:.1f} MB)")


def _export_biw():
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    for src in (INPUT_MATRICES_K, INPUT_MATRICES_M):
        if not src.exists():
            raise FileNotFoundError(
                f"Matrix file not found:\n  {src}\n"
                "Check the 'matrices_K/M' paths in config.py."
            )
        dest = OUTPUT_DIR / src.name
        shutil.copy2(src, dest)
        size_mb = dest.stat().st_size / 1024 / 1024
        print(f"Copied {src.name} → {dest}  ({size_mb:.1f} MB)")


def main():
    print(f"Variant : {VARIANT}")
    print(f"Output  : {OUTPUT_DIR}\n")

    if VARIANT == "TB":
        _export_tb()
    else:
        _export_biw()


if __name__ == '__main__':
    main()
